//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketAnalyze
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductRelationship
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual stock stock { get; set; }
    }
}
